inventory/inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("inventoryapp.urls")),
]

inventory/inventoryapp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.home_page, name="home"),
    path("addproduct/", views.addproduct_page, name="addproduct"),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('my_po/', views.my_po, name="my_po"),
    path('my_po_details/<int:pk>/', views.my_po_details, name="my_po_details"),
    path("login/", views.login_page, name="login"),
    path("register/", views.registersupplier_page, name="register"),
    path("logout/", views.logout_page, name="logout"),

    # === SUPPLIERS' URLS ===
    path("generate_po/", views.generate_po, name="generate_po"),
    path('my_generated_po/', views.my_generated_po, name='my_generated_po'),
    path('my_generated_po_details/<int:pk>/', views.my_generated_po_details, name='my_generated_po_details'),
    path("products_list/", views.products_list, name="products_list"),

    # === UI CUSTOMIZATION URLS ===
    path("customization/", views.customization, name="customization"),
    path('customization/navigation/', views.navbar_customization, name='navbar_customization'),
    path('customization/save_navbar/', views.save_navbar_customization, name='save_navbar_customization'),
    path('customization/login/', views.login_customization, name='login_customization'),
    path('customization/save_login/', views.save_login_customization, name='save_login_customization'),
    path('customization/mainpage/', views.mainpage_customization, name='mainpage_customization'),
    path('customization/mainpage/save_mainpage', views.save_mainpage_customization, name='save_mainpage_customization'),
    path('customization/logo', views.logo_customization, name="logo_customization"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/inventoryapp/models.py
from django.db import models
from django.contrib.auth.models import User

# === SUPPLIER PROFILE ===
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100, blank=True, null=True)
    is_supplier = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


# === PRODUCT DATABASE ===
class Products(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=255, default="None")
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity_in_stock = models.IntegerField()
    unit_of_measurement = models.CharField(max_length=50)
    reorder_level = models.IntegerField()
    expiration_date = models.DateField(null=True, blank=True)
    supplier = models.ForeignKey(UserProfile, on_delete=models.CASCADE, limit_choices_to={'is_supplier': True})
    
    def __str__(self):
        return self.name
    

# === PURCHASE ORDERS ===
class PurchaseOrder(models.Model):
    order_number = models.CharField(max_length=20, unique=True)
    company_name = models.CharField(max_length=100)
    company_address = models.CharField(max_length=255)
    supplier_name = models.CharField(max_length=100)
    supplier_address = models.CharField(max_length=255)
    order_status = models.CharField(
        max_length=20,
        choices=[
            ('PENDING', 'Pending'),
            ('ACCEPTED', 'Accept'),
            ('REJECTED', 'Reject'),
        ],
        null=True, blank=True
    )
    date_issued = models.DateField(auto_now_add=True)
    total_amount_payable = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchase_orders')
    name = models.CharField(max_length=100, null=True, blank=True)
    category = models.CharField(max_length=50, null=True)
    description = models.TextField(null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    unit_of_measurement = models.CharField(max_length=20, null=True, blank=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.subtotal = self.quantity * self.unit_price
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


# === MODELS FOR UI CUSTOMIZATIONS ===
class NavBarCustomization(models.Model):
    background_color = models.CharField(max_length=20, default='Blue')
    company_text_color = models.CharField(max_length=20, default='White')
    button_text_color = models.CharField(max_length=20, default='White')
    company_name = models.CharField(max_length=100, default='Company Name')

    def __str__(self):
        return 'NavBar Customization'
    
class LoginCustomization(models.Model):
    background_color = models.CharField(max_length=20, default='White')
    box_color = models.CharField(max_length=20, default='white')
    title_text_color = models.CharField(max_length=20, default='Black')
    input_text_color = models.CharField(max_length=20, default='Black')
    button_color = models.CharField(max_length=20, default='Green')

    def __str__(self):
        return 'Login Customization'

class MainPageCustomization(models.Model):
    background_color = models.CharField(max_length=20, default='White')
    box_color = models.CharField(max_length=20, default='white')
    title_text_color = models.CharField(max_length=20, default='Black')
    table_header_text_color = models.CharField(max_length=20, default='Black')
    table_header_color = models.CharField(max_length=20, default='#f4f4f4')
    table_text_color = models.CharField(max_length=20, default='Black')
    table_row_color = models.CharField(max_length=20, default='#fff')

    def __str__(self):
        return 'Main Page Customization'
    
class CompanyLogo(models.Model):
    logo = models.ImageField(upload_to="logo/", null=True, blank=True)

    def __str__(self):
        return 'Image Logo'

inventory/inventoryapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse

import random
import string
from django.utils import timezone

from .forms import UserRegistrationForm, AddProductForm, PurchaseOrderForm, PurchaseOrderStatusForm, LogoForm
from .models import UserProfile, Products, NavBarCustomization, LoginCustomization, MainPageCustomization, CompanyLogo, PurchaseOrder

def registersupplier_page(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            company_name = form.cleaned_data['company_name']
            user = User.objects.create_user(username=username, password=password)
            profile = UserProfile(user=user, company_name=company_name)
            profile.save()
            return redirect('login')
        
    else:
        form = UserRegistrationForm()

    CLcustomization, created = CompanyLogo.objects.get_or_create()

    if CLcustomization is None:
        CLcustomization = CompanyLogo.objects.create()

    customization = LoginCustomization.objects.first()
    if customization is None:
        customization = LoginCustomization.objects.create()

    return render(request, 'authentication/register.html', {'form': form, 'CLcustomization': CLcustomization, 'customization': customization})


def login_page(request):
    if request.user.is_authenticated:
        logout(user.request)
        return redirect('login')
    
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            
            else:
                messages.error(request, "Invalid login credentials!")

        CLcustomization, created = CompanyLogo.objects.get_or_create()

        if CLcustomization is None:
            CLcustomization = CompanyLogo.objects.create()

        customization = LoginCustomization.objects.first()
        if customization is None:
            customization = LoginCustomization.objects.create()

        return render(request, "authentication/login.html", {'CLcustomization': CLcustomization, 'customization': customization})


@login_required(login_url="/login/")
def logout_page(request):
    logout(request)
    return redirect("login")


@login_required(login_url="/login/")
def home_page(request):
    products = Products.objects.all()

    CLcustomization = CompanyLogo.objects.first()
    if CLcustomization is None:
        CLcustomization = CompanyLogo.objects.create()

    customization = NavBarCustomization.objects.first()
    if customization is None:
        customization = NavBarCustomization.objects.create()

    Mcustomization = MainPageCustomization.objects.first()
    if Mcustomization is None:
        Mcustomization = MainPageCustomization.objects.create()

    PO = PurchaseOrder.objects.filter(order_status=None)
    countPO = PO.count()
    
    return render(request, "home/homepage.html", {
        'products': products,

        'CLcustomization': CLcustomization, 
        'customization': customization,
        'Mcustomization': Mcustomization,
        'countPO': countPO
    })


@login_required(login_url="/login/")
def addproduct_page(request):
    if request.method == "POST":
        form = AddProductForm(request.POST)
        if form.is_valid():
            Products.objects.create(**form.cleaned_data)
            return redirect('home')  
    else:
        form = AddProductForm()

    CLcustomization = CompanyLogo.objects.first() or CompanyLogo.objects.create()
    customization = NavBarCustomization.objects.first() or NavBarCustomization.objects.create()
    Mcustomization = MainPageCustomization.objects.first() or MainPageCustomization.objects.create()
    
    return render(request, "home/addproduct.html", {'CLcustomization': CLcustomization, 'form': form, 'customization': customization, 'Mcustomization': Mcustomization})


@login_required(login_url="/login/")
def update_product(request, product_id):
    product = get_object_or_404(Products, pk=product_id)

    if request.method == "POST":
        form = AddProductForm(request.POST)
        if form.is_valid():
            product.name = form.cleaned_data['name']
            product.description = form.cleaned_data['description']
            product.price = form.cleaned_data['price']
            product.quantity_in_stock = form.cleaned_data['quantity_in_stock']
            product.unit_of_measurement = form.cleaned_data['unit_of_measurement']
            product.reorder_level = form.cleaned_data['reorder_level']
            product.expiration_date = form.cleaned_data['expiration_date']
            product.supplier = form.cleaned_data['supplier']
            product.save()
            return redirect('home')
    else:
        form = AddProductForm(initial={
            'name': product.name,
            'category': product.category,
            'description': product.description,
            'price': product.price,
            'quantity_in_stock': product.quantity_in_stock,
            'unit_of_measurement': product.unit_of_measurement,
            'reorder_level': product.reorder_level,
            'expiration_date': product.expiration_date,
            'supplier': product.supplier
        })

    CLcustomization = CompanyLogo.objects.first() or CompanyLogo.objects.create()
    customization = NavBarCustomization.objects.first() or NavBarCustomization.objects.create()

    return render(request, "home/update_product.html", {'CLcustomization': CLcustomization, 'form': form, 'customization': customization})


@login_required(login_url="/login/")
def delete_product(request, product_id):
    product = get_object_or_404(Products, pk=product_id)

    product.delete()
    return redirect('home')



@login_required(login_url="/login/")
def my_po(request):
    purchase_orders = PurchaseOrder.objects.all().order_by('-date_issued')

    CLcustomization = CompanyLogo.objects.first()

    if CLcustomization is None:
        CLcustomization = CompanyLogo.objects.create()

    customization = NavBarCustomization.objects.first()
    if customization is None:
        customization = NavBarCustomization.objects.create()

    return render(request, "home/my_po.html", {'CLcustomization': CLcustomization, 'purchase_orders': purchase_orders, 'customization': customization})


@login_required(login_url="/login/")
def my_po_details(request, pk):
    purchase_order = get_object_or_404(PurchaseOrder, pk=pk)
    if request.method == 'POST':
        form = PurchaseOrderStatusForm(request.POST, instance=purchase_order)
        if form.is_valid():
            form.save()
            return redirect('my_po')
    else:
        form = PurchaseOrderStatusForm(instance=purchase_order)

    CLcustomization = CompanyLogo.objects.first()

    if CLcustomization is None:
        CLcustomization = CompanyLogo.objects.create()

    customization = NavBarCustomization.objects.first()
    if customization is None:
        customization = NavBarCustomization.objects.create()
    
    return render(request, 'home/my_po_details.html', {'CLcustomization': CLcustomization, 'purchase_order': purchase_order, 'form': form, 'customization': customization})


# === FOR SUPPLIERS ===
from django.db import connections

def generate_order_number():
    timestamp = timezone.now().strftime('%Y%m%d%H%M%S')
    random_string = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
    order_number = f'{timestamp}-{random_string}'
    return order_number

@login_required(login_url="/login/")
def generate_po(request):
    if request.method == 'POST':
        form = PurchaseOrderForm(request.POST)
        if form.is_valid():
            purchase_order = form.save(commit=False)
            purchase_order.created_by = request.user
            purchase_order.order_number = generate_order_number()

            purchase_order.total_amount_payable = purchase_order.quantity * purchase_order.unit_price
            purchase_order.save()
            return redirect('products_list')
        else:
            for field, errors in form.errors.items():
                print(f"Error in field '{field}': {', '.join(errors)}")
    else:
        form = PurchaseOrderForm()

    CLcustomization = CompanyLogo.objects.first()
    if CLcustomization is None:
        CLcustomization = CompanyLogo.objects.create()

    customization = NavBarCustomization.objects.first()
    if customization is None:
        customization = NavBarCustomization.objects.create()
    
    return render(request, "purchaseorders/generate_po.html", {'CLcustomization': CLcustomization, 'customization': customization, 'form': form})


@login_required(login_url="/login/")
def my_generated_po(request):
    purchase_orders = PurchaseOrder.objects.filter(created_by=request.user).order_by('-date_issued') 

    CLcustomization = CompanyLogo.objects.first()

    if CLcustomization is None:
        CLcustomization = CompanyLogo.objects.create()

    customization = NavBarCustomization.objects.first()
    if customization is None:
        customization = NavBarCustomization.objects.create()

    return render(request, "purchaseorders/my_generated_po.html", {'CLcustomization': CLcustomization, 'purchase_orders': purchase_orders, 'customization': customization})


@login_required(login_url="/login/")
def my_generated_po_details(request, pk):
    purchase_order = get_object_or_404(PurchaseOrder, pk=pk)

inventory/inventoryapp/templates/purchaseorders/generate_po.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meats List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'suppliercss/supplier.css' %}">

    <style>
        .navigation-bar {
            background-color: {{ customization.background_color }};
        }

        .navigation-bar {
            color: {{ customization.company_text_color }};
        }

        .navigation-bar h3 {
            color: {{ customization.button_text_color }}
        }

        .navigation-bar button {
            color: {{ customization.button_text_color }};
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>

    <div class="navigation-bar">
        {% if CLcustomization.logo %}
            <img src="{{ CLcustomization.logo.url }}" class="nav-logo" height="50px" width="50px" alt="Logo">
        {% else %}
            <p>No Image</p>
        {% endif %}
        <h1>Generate {{ customization.company_name }}'s Sales Order</h1>

        <div class="navigation-bar-buttons">
            <a href="{% url 'products_list' %}"><h3>Home</h3></a>
            <a href="{% url 'generate_po' %}"><h3>Generate Sales Order</h3></a>
            <a href="{% url 'my_generated_po' %}"><h3>My Orders</h3></a>

            <form action="{% url 'logout' %}">
                <button>Logout</button>
            </form>
        </div>
    </div>

    <div class="form-container">
        <h1>Create Sales Order</h1>
        <form action="{% url 'generate_po' %}" method="POST" class="purchase-order-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_company_name">Company Name:</label>
                {{ form.company_name }}
                {% if form.errors.company_name %}
                    <p class="error">1{{ form.errors.company_name }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_company_address">Company Address:</label>
                {{ form.company_address }}
                {% if form.errors.company_address %}
                    <p class="error">2{{ form.errors.company_address }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_supplier_name">Supplier Name:</label>
                {{ form.supplier_name }}
                {% if form.errors.supplier_name %}
                    <p class="error">3{{ form.errors.supplier_name }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_supplier_address">Supplier Address:</label>
                {{ form.supplier_address }}
                {% if form.errors.supplier_address %}
                    <p class="error">4{{ form.errors.supplier_address }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_name">Product Name:</label>
                {{ form.name }}
                {% if form.errors.name %}
                    <p class="error">5{{ form.errors.name }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_category">Product Category:</label>
                {{ form.category }}
                {% if form.errors.category %}
                    <p class="error">6{{ form.errors.category }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_description">Description:</label>
                {{ form.description }}
                {% if form.errors.description %}
                    <p class="error">7{{ form.errors.description }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_quantity">Quantity:</label>
                {{ form.quantity }}
                {% if form.errors.quantity %}
                    <p class="error">8{{ form.errors.quantity }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_unit_of_measurement">Unit of Measurement:</label>
                {{ form.unit_of_measurement }}
                {% if form.errors.unit_of_measurement %}
                    <p class="error">9{{ form.errors.unit_of_measurement }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_unit_price">Unit Price:</label>
                {{ form.unit_price }}
                {% if form.errors.unit_price %}
                    <p class="error">10{{ form.errors.unit_price }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <button type="submit">Save Purchase Order</button>
            </div>
        </form>
    </div>

</body>
</html>

inventory/inventoryapp/templates/purchaseorders/my_generated_po.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'suppliercss/supplier.css' %}">

    <style>
        .navigation-bar {
            background-color: {{ customization.background_color }};
        }

        .navigation-bar {
            color: {{ customization.company_text_color }};
        }

        .navigation-bar h3 {
            color: {{ customization.button_text_color }}
        }

        .navigation-bar button {
            color: {{ customization.button_text_color }};
        }
    </style>
</head>
<body>
    <div class="navigation-bar">
        {% if CLcustomization.logo %}
            <img src="{{ CLcustomization.logo.url }}" class="nav-logo" height="50px" width="50px" alt="Logo">
        {% else %}
            <p>No Image</p>
        {% endif %}
        <h1>{{ customization.company_name }}'s Sales Order</h1>

        <div class="navigation-bar-buttons">
            {% if request.user.username == 'meat' %}
                <a href="{% url 'meats_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'baked' %}
                <a href="{% url 'baked_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'beverages' %}
                <a href="{% url 'beverages_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'condiments' %}
                <a href="{% url 'condiments_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'dairy' %}
                <a href="{% url 'dairy_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'dry' %}
                <a href="{% url 'dry_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'packaging' %}
                <a href="{% url 'packaging_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'plants' %}
                <a href="{% url 'plants_list' %}"><h3>Home</h3></a>
            {% endif %}
            <a href="{% url 'products_list' %}"><h3>Home</h3></a>
            <a href="{% url 'generate_po' %}"><h3>Generate Sales Order</h3></a>
            <a href="{% url 'my_generated_po' %}"><h3>My Orders</h3></a>

            <form action="{% url 'logout' %}">
                <button>Logout</button>
            </form>
        </div>
    </div>

    <div class="purchase-orders-container">
        <h1>My Sales Orders</h1>
        {% if purchase_orders %}
            {% for purchase_order in purchase_orders %}
                <div class="purchase-order">
                    <div class="order-details">
                        <p>Order Number: {{ purchase_order.order_number }}</p>
                        <p>Company Name: {{ purchase_order.company_name }}</p>
                        <p>Supplier Name: {{ purchase_order.supplier_name }}</p>
                        <p>Total Amount Payable: {{ purchase_order.total_amount_payable }}</p>
                        <p>Status: {{ purchase_order.get_order_status_display }}</p>
                    </div>
                    <div class="view-details-button">
                        <form action="{% url 'my_generated_po_details' pk=purchase_order.pk %}" method="GET">
                            <button type="submit">View Details</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No sales orders found.</p>
        {% endif %}
    </div>
</body>
</html>

inventory/inventoryapp/templates/purchaseorders/my_generated_po_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meats List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'suppliercss/supplier.css' %}">

    <style>
        .navigation-bar {
            background-color: {{ customization.background_color }};
        }

        .navigation-bar {
            color: {{ customization.company_text_color }};
        }

        .navigation-bar h3 {
            color: {{ customization.button_text_color }}
        }

        .navigation-bar button {
            color: {{ customization.button_text_color }};
        }
    </style>
</head>
<body>

    <div class="navigation-bar">
        {% if CLcustomization.logo %}
            <img src="{{ CLcustomization.logo.url }}" class="nav-logo" height="50px" width="50px" alt="Logo">
        {% else %}
            <p>No Image</p>
        {% endif %}
        <h1>{{ customization.company_name }}'s Sales Order Details</h1>

        <div class="navigation-bar-buttons">
            {% if request.user.username == 'meat' %}
                <a href="{% url 'meats_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'baked' %}
                <a href="{% url 'baked_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'beverages' %}
                <a href="{% url 'beverages_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'condiments' %}
                <a href="{% url 'condiments_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'dairy' %}
                <a href="{% url 'dairy_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'dry' %}
                <a href="{% url 'dry_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'packaging' %}
                <a href="{% url 'packaging_list' %}"><h3>Home</h3></a>
            {% elif request.user.username == 'plants' %}
                <a href="{% url 'plants_list' %}"><h3>Home</h3></a>
            {% endif %}
            <a href="{% url 'products_list' %}"><h3>Home</h3></a>
            <a href="{% url 'generate_po' %}"><h3>Generate Sales Order</h3></a>
            <a href="{% url 'my_generated_po' %}"><h3>My Orders</h3></a>

            <form action="{% url 'logout' %}">
                <button>Logout</button>
            </form>
        </div>
    </div>

    <div class="purchase-order-detail">
        <h1>Purchase Order Detail</h1>
        <form method="post">
            {% csrf_token %}

            <div class="top-part">
                <div class="top-half-part1">
                    <div class="detail-item">
                        <label for="company_name">Company Name:</label>
                        <span>{{ purchase_order.company_name }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="company_address">Company Address:</label>
                        <span>{{ purchase_order.company_address }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="supplier_name">Supplier Name:</label>
                        <span>{{ purchase_order.supplier_name }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="supplier_address">Supplier Address:</label>
                        <span>{{ purchase_order.supplier_address }}</span>
                    </div>
                </div>

                <div class="top-half-part2">
                    <div class="detail-item">
                        <label for="date_issued">Date Issued:</label>
                        <span>{{ purchase_order.date_issued }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="order_number">Order Number:</label>
                        <span>{{ purchase_order.order_number }}</span>
                    </div>
                </div>  
            </div>

            <hr>

            <div class="mid-part">
                <div class="mid-half-part1">
                    <div class="detail-item">
                        <label for="name">Product Name:</label>
                        <span>{{ purchase_order.name }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="category">Category:</label>
                        <span>{{ purchase_order.category }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="description">Description:</label>
                        <span>{{ purchase_order.description }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="quantity">Quantity:</label>
                        <span>{{ purchase_order.quantity }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="unit_of_measurement">Unit of Measurement:</label>
                        <span>{{ purchase_order.unit_of_measurement }}</span>
                    </div>
                </div>
                
                <div class="mid-half-part2">
                    <div class="detail-item">
                        <label for="unit_price">Unit Price:</label>
                        <span>₱ {{ purchase_order.unit_price }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="subtotal">Subtotal:</label>
                        <span>₱ {{ purchase_order.subtotal }}</span>
                    </div>
                </div>  
            </div>
            
            <hr>

            <div class="bot-part-flex-end">
                <div class="bot-part">
                    <div class="detail-item">
                        <label for="total_amount_payable">Total Amount Payable:</label>
                        <span>₱ {{ purchase_order.total_amount_payable }}</span>
                    </div>
                    <div class="detail-item">
                        <label for="order_status">Order Status:</label>
                        <span>{{ purchase_order.get_order_status_display }}</span>
                    </div>

                </div>
            </div>

        </form>
    </div>
</body>
</html>